DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NROMATRICULA VARCHAR(50) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, '123', 'SOFIA','MILLAN');
INSERT INTO ODONTOLOGOS VALUES (DEFAULT, '456', 'OMAR','ROLDAN');